-- SPCS Restricted Callers Rights Lab - Initial Setup
-- This script sets up the foundational resources for the lab

-- Clean up existing resources if they exist
USE ROLE ACCOUNTADMIN;

-- Drop existing resources (ignore errors if they don't exist)
DROP COMPUTE POOL IF EXISTS SPCS_RESTRICTED_POOL;
DROP WAREHOUSE IF EXISTS SPCS_LAB_WH;
DROP DATABASE IF EXISTS SPCS_RESTRICTED_DEMO;
DROP ROLE IF EXISTS CLIENT_A_ANALYST;
DROP ROLE IF EXISTS CLIENT_B_ANALYST;
DROP ROLE IF EXISTS PLATFORM_OWNER;

-- Create lab warehouse
CREATE WAREHOUSE SPCS_LAB_WH WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    COMMENT = 'Warehouse for SPCS Restricted Callers Rights Lab';

-- Create lab database and schema
CREATE DATABASE SPCS_RESTRICTED_DEMO
    COMMENT = 'Database for SPCS Restricted Callers Rights Lab';

USE DATABASE SPCS_RESTRICTED_DEMO;

CREATE SCHEMA FINANCIAL_DATA
    COMMENT = 'Schema containing financial transaction data';

CREATE SCHEMA CONTAINER_REGISTRY
    COMMENT = 'Schema for container registry';

-- Create image repository
USE SCHEMA CONTAINER_REGISTRY;

CREATE IMAGE REPOSITORY analytics_repo
    COMMENT = 'Repository for analytics service container images';

-- Switch to financial data schema
USE SCHEMA FINANCIAL_DATA;

-- Create roles for multi-tenant scenario
CREATE ROLE CLIENT_A_ANALYST
    COMMENT = 'Role for Client A financial analysts';
    
CREATE ROLE CLIENT_B_ANALYST  
    COMMENT = 'Role for Client B financial analysts';
    
CREATE ROLE PLATFORM_OWNER
    COMMENT = 'Role that owns the SPCS service and manages platform';

-- Grant basic privileges to roles
GRANT USAGE ON WAREHOUSE SPCS_LAB_WH TO ROLE CLIENT_A_ANALYST;
GRANT USAGE ON WAREHOUSE SPCS_LAB_WH TO ROLE CLIENT_B_ANALYST;
GRANT USAGE ON WAREHOUSE SPCS_LAB_WH TO ROLE PLATFORM_OWNER;

GRANT USAGE ON DATABASE SPCS_RESTRICTED_DEMO TO ROLE CLIENT_A_ANALYST;
GRANT USAGE ON DATABASE SPCS_RESTRICTED_DEMO TO ROLE CLIENT_B_ANALYST;
GRANT USAGE ON DATABASE SPCS_RESTRICTED_DEMO TO ROLE PLATFORM_OWNER;

GRANT USAGE ON SCHEMA FINANCIAL_DATA TO ROLE CLIENT_A_ANALYST;
GRANT USAGE ON SCHEMA FINANCIAL_DATA TO ROLE CLIENT_B_ANALYST;
GRANT USAGE ON SCHEMA FINANCIAL_DATA TO ROLE PLATFORM_OWNER;

-- Grant platform owner additional privileges
GRANT ALL PRIVILEGES ON DATABASE SPCS_RESTRICTED_DEMO TO ROLE PLATFORM_OWNER;
GRANT ALL PRIVILEGES ON SCHEMA FINANCIAL_DATA TO ROLE PLATFORM_OWNER;
GRANT ALL PRIVILEGES ON SCHEMA CONTAINER_REGISTRY TO ROLE PLATFORM_OWNER;
GRANT USAGE ON IMAGE REPOSITORY analytics_repo TO ROLE PLATFORM_OWNER;

-- Grant roles to current user for lab execution
GRANT ROLE CLIENT_A_ANALYST TO USER CURRENT_USER();
GRANT ROLE CLIENT_B_ANALYST TO USER CURRENT_USER();
GRANT ROLE PLATFORM_OWNER TO USER CURRENT_USER();

-- Create compute pool for containers
CREATE COMPUTE POOL SPCS_RESTRICTED_POOL
    MIN_NODES = 1
    MAX_NODES = 3
    INSTANCE_FAMILY = CPU_X64_XS
    COMMENT = 'Compute pool for SPCS Restricted Callers Rights Lab';

-- Grant compute pool usage to platform owner
GRANT USAGE ON COMPUTE POOL SPCS_RESTRICTED_POOL TO ROLE PLATFORM_OWNER;
GRANT MONITOR ON COMPUTE POOL SPCS_RESTRICTED_POOL TO ROLE PLATFORM_OWNER;

SHOW ROLES;
SHOW WAREHOUSES;
SHOW DATABASES;
SHOW COMPUTE POOLS; 